---
# Playbook Start, run for all hosts, become sudo
- hosts: all
  become: true
  tasks:

   - name: Add online hosts only to group
     add_host:
       group: online_hosts
     when: ping == "pong"


# Install Neofetch, net-tools, qemu, and update repo for all servers
#  - name: Install Neofetch net-tools qemu and update the repo
#    package:
#      name:
#        - "{{ neofetch_package }}"
#        - "{{ nettool_package }}"
#        - "{{ qemu_package }}"
#      state: latest
#      update_cache: yes

#  - name: Install stuff for Ubuntu
#    apt:
#      name:
#        - neofetch
#        - net-tools
#        - qemu-guest-agent
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

#  - name: Install Stuff for Manjaro
#    pacman:
#      name:
#        - neofetch
#        - net-tools
#        - qemu-guest-agent
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Archlinux"
